### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by chenshanchao** [Alpha-su/dbpolicy_crawl#1]
在连接数据库的时候我将库换成自己本地的库，但是没有找到一份可以创建表结构的sql文件，您可以提供一份吗

**Comment by Alpha-su** [comment]
这个涉及到多个表，表结构复杂，有些和我的实际业务相关，您未必能用上，建议参考源代码中操作mysql进行insert的语句，或许能大概明白表结构和设计
